<?php

namespace Matteo\LearnBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CardboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardboxRepository extends EntityRepository
{
    public function findAllPublicCardboxes() 
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT p FROM MatteoLearnBundle:Cardbox p WHERE p.is_private = 0 OR p.is_private IS NULL')
                    ->getResult();
    }
    
    public function findCardboxesWithCategoryId($categoryId)
    {
        return $this->createQueryBuilder('c')
            ->where('c.category = :category')
            ->setParameter('category', $categoryId)
            ->getQuery()
            ->getResult();
    }
    
    public function getIntroductionCardbox()
    {
        return $this->createQueryBuilder('c')
            ->where('c.name = :name')
            ->setParameter('name', 'Get Started')
            ->getQuery()
            ->getResult();
    }
}
